language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-came' ]; then cd .. && eval "mv $currentfolder generator-came" && cd generator-came; fi

